# Generated by Django 5.2.8 on 2025-11-15 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='کد تخفیف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد تخفیف')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ ثابت تخفیف')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع معتبر بودن')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='پایان معتبر بودن')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد اکثر استفاده')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ استفاده')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupon.coupon', verbose_name='کوپن')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'استفاده از کوپن',
                'verbose_name_plural': 'استفاده\u200cهای کوپن',
            },
        ),
    ]
