# Generated by Django 5.2.8 on 2025-11-15 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100, verbose_name='درگاه/پرداخت\u200cکننده')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('INIT', 'آغاز'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق')], default='INIT', max_length=32, verbose_name='وضعیت پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='شناسه تراکنش')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انجام')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
    ]
