# Generated by Django 5.2.8 on 2025-11-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('position',), 'verbose_name': 'گزینه', 'verbose_name_plural': 'گزینه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'ordering': ('position',), 'verbose_name': 'مقدار گزینه', 'verbose_name_plural': 'مقادیر گزینه\u200cها'},
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='نام گزینه'),
        ),
        migrations.AlterField(
            model_name='option',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='اولویت نمایش'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='options.option', verbose_name='گزینه'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='اولویت نمایش'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='value',
            field=models.CharField(max_length=150, verbose_name='مقدار'),
        ),
    ]
