# Generated by Django 5.2.8 on 2025-11-15 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='روش ارسال')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='کد')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه ارسال')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=200, verbose_name='شماره پیگیری')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='order.order', verbose_name='سفارش')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.shippingmethod', verbose_name='روش ارسال')),
            ],
            options={
                'verbose_name': 'ارسال',
                'verbose_name_plural': 'ارسال\u200cها',
            },
        ),
    ]
