# Generated by Django 5.2.8 on 2025-11-15 22:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0002_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'موجودی', 'verbose_name_plural': 'موجودی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='stockoperation',
            options={'verbose_name': 'عملیات موجودی', 'verbose_name_plural': 'عملیات موجودی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'انبار', 'verbose_name_plural': 'انبارها'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.productvariant', verbose_name='واریانت محصول'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='note',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='op_type',
            field=models.CharField(choices=[('IN', 'ورود'), ('OUT', 'خروج'), ('ADJ', 'تعدیل')], max_length=3, verbose_name='نوع عملیات'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='quantity',
            field=models.IntegerField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='product.productvariant', verbose_name='واریانت محصول'),
        ),
        migrations.AlterField(
            model_name='stockoperation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='inventory.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام انبار'),
        ),
    ]
